CREATE TABLE articulo (
     id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY , 
     referencia      VARCHAR (20) NOT NULL , 
     color           VARCHAR (10) NOT NULL , 
     material        VARCHAR (10) NOT NULL , 
     descripcion     VARCHAR (30) NOT NULL , 
     precioUnitario  INTEGER NOT NULL , 
     cantidad        INTEGER NOT NULL
);

ALTER TABLE articulo ADD CONSTRAINT articulo_pk PRIMARY KEY ( id );

CREATE TABLE cliente (
     id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY ,  
     nombre         VARCHAR (20) NOT NULL , 
     identificador  INTEGER NOT NULL , 
     estadoCliente  VARCHAR (10) NOT NULL
);

ALTER TABLE cliente ADD CONSTRAINT cliente_pk PRIMARY KEY ( id );

CREATE TABLE ventas (
    id                 NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    cliente_id        INTEGER NOT NULL,
    articulo_id        INTEGER NOT NULL,
    FECHADEVENTA       DATE NOT NULL ENABLE,
    CANTIDAD           INTEGER NOT NULL,
    TOTAL              INTEGER NOT NULL
);

ALTER TABLE ventas ADD CONSTRAINT ventas_pk PRIMARY KEY ( id);



ALTER TABLE ventas
    ADD CONSTRAINT ventas_articulo_fk FOREIGN KEY ( articulo_id )
        REFERENCES articulo ( id );

ALTER TABLE ventas
    ADD CONSTRAINT ventas_cliente_fk FOREIGN KEY ( cliente_id )
        REFERENCES cliente ( id );
